image:
- Visual Studio 2015
      
platform: x64
configuration: Release

init:
    - git config --global core.autocrlf input
    - copy freetype-msvc\x86-windows-static-crt.cmake c:\tools\vcpkg\triplets
    - copy freetype-msvc\x64-windows-static-crt.cmake c:\tools\vcpkg\triplets

build_script:
  - vcpkg install freetype:x86-windows-static-crt
  - vcpkg install freetype:x64-windows-static-crt
  - 7z a -r freetype_2.8.1_x86_windows_dll.zip C:\tools\vcpkg\packages\freetype_x86-windows-static-crt\*
  - 7z a -r freetype_2.8.1_x64_windows_dll.zip C:\tools\vcpkg\packages\freetype_x64-windows-static-crt\*

artifacts:
  - path: freetype_2.8.1_x86_windows_dll.zip
    name: freetype 2.8.1 x86 DLL
  - path: freetype_2.8.1_x64_windows_dll.zip
    name: freetype 2.8.1 x64 DLL
